//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\franc\Documents\Visual Studio 2019\Projects\VooDo\VooDo\VooDo\Parsing\ANTLR\\VooDo.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace VooDo.Parsing.ANTLR.Generated {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VooDoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IVooDoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>MulOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulOpExpr([NotNull] VooDoParser.MulOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BoolLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLitExpr([NotNull] VooDoParser.BoolLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogNotExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogNotExpr([NotNull] VooDoParser.LogNotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GtOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGtOpExpr([NotNull] VooDoParser.GtOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DivOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivOpExpr([NotNull] VooDoParser.DivOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PosOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPosOpExpr([NotNull] VooDoParser.PosOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MemOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemOpExpr([NotNull] VooDoParser.MemOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLitExpr([NotNull] VooDoParser.StringLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameExpr([NotNull] VooDoParser.NameExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EqOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqOpExpr([NotNull] VooDoParser.EqOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexExpr([NotNull] VooDoParser.IndexExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinIntLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinIntLitExpr([NotNull] VooDoParser.BinIntLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwLstOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwLstOpExpr([NotNull] VooDoParser.BwLstOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwOrOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwOrOpExpr([NotNull] VooDoParser.BwOrOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexIntLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexIntLitExpr([NotNull] VooDoParser.HexIntLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CastExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpr([NotNull] VooDoParser.CastExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullableMemOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullableMemOpExpr([NotNull] VooDoParser.NullableMemOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwXorOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwXorOpExpr([NotNull] VooDoParser.BwXorOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogOrOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogOrOpExpr([NotNull] VooDoParser.LogOrOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SubOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubOpExpr([NotNull] VooDoParser.SubOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullCoalOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullCoalOpExpr([NotNull] VooDoParser.NullCoalOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLitExpr([NotNull] VooDoParser.NullLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfElseOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseOpExpr([NotNull] VooDoParser.IfElseOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LeOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeOpExpr([NotNull] VooDoParser.LeOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegOpExpr([NotNull] VooDoParser.NegOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwNegExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwNegExpr([NotNull] VooDoParser.BwNegExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwRstOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwRstOpExpr([NotNull] VooDoParser.BwRstOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GroupExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupExpr([NotNull] VooDoParser.GroupExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OctIntLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOctIntLitExpr([NotNull] VooDoParser.OctIntLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CallOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallOpExpr([NotNull] VooDoParser.CallOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogAndOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogAndOpExpr([NotNull] VooDoParser.LogAndOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GeOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeOpExpr([NotNull] VooDoParser.GeOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LtOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLtOpExpr([NotNull] VooDoParser.LtOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModOpExpr([NotNull] VooDoParser.ModOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SumOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumOpExpr([NotNull] VooDoParser.SumOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NeqOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNeqOpExpr([NotNull] VooDoParser.NeqOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RealLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealLitExpr([NotNull] VooDoParser.RealLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BwAndOpExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBwAndOpExpr([NotNull] VooDoParser.BwAndOpExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DecIntLitExpr</c>
	/// labeled alternative in <see cref="VooDoParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecIntLitExpr([NotNull] VooDoParser.DecIntLitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SequenceStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequenceStat([NotNull] VooDoParser.SequenceStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfElseStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseStat([NotNull] VooDoParser.IfElseStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStat([NotNull] VooDoParser.WhileStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForeachStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStat([NotNull] VooDoParser.ForeachStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignmentStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStat([NotNull] VooDoParser.AssignmentStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LinkStat</c>
	/// labeled alternative in <see cref="VooDoParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkStat([NotNull] VooDoParser.LinkStatContext context);
}
} // namespace VooDo.Parsing.ANTLR.Generated
