<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>voodo</string>
   </array>
  <key>name</key>
  <string>VooDo</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.VooDo</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#using</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
       </array>
    </dict>
    <key>block</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#block__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>block__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statement</string>
        </dict>
       </array>
    </dict>
    <key>builtin_type</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(bool|short|ushort|int|uint|long|ulong|float|double|decimal|char|string|object)\b)</string>
          <key>name</key>
          <string>entity.name.type storage.type keyword.type support.type.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>char</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#char__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>char__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{0027}\x{005c}])</string>
          <key>name</key>
          <string>constant.character.VooDo</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#escaped_char</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#invalid</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#line_comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multiline_comment</string>
        </dict>
       </array>
    </dict>
    <key>escaped_char</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((\\(([\x{005c}\x{0027}\x{0022}0abfnrtv])|(x([\dA-Fa-f]){1,4})|(u([\dA-Fa-f]){4})|(U([\dA-Fa-f]){8}))))</string>
          <key>name</key>
          <string>constant.character.escape.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#char</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#parentheses</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#builtin_type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression_invalid_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression_punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#invalid</string>
        </dict>
       </array>
    </dict>
    <key>expression_invalid_keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(const|else|global|if|return)\b)</string>
          <key>name</key>
          <string>invalid.broken.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>expression_keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(as|default|false|glob|init|in|is|new|null|out|ref|true|var)\b)</string>
          <key>name</key>
          <string>keyword.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>expression_punctuation</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([.\x{002c}\x{003a}\x{003f}\x{002b}\-\x{002f}\x{002a}\x{0025}\x{0026}\x{007c}\x{005e}\x{0021}\x{007e}\x{003c}\x{003e}\x{005b}\]\x{0024}]|[\x{003c}\x{003e}\x{003d}\x{0021}]=)</string>
          <key>name</key>
          <string>punctuation.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>identifier</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(@?)(__VooDo_Reserved[a-zA-Z_][a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.VooDo</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(@?)([a-zA-Z_][a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>invalid</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.broken.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.VooDo</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.VooDo</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multiline_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(//)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.VooDo</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.VooDo</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multiline_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((((\d(_*\d)*)?\.\d(_*\d)*([eE](\+|-)?\d(_*\d)*)?([fFsFmM])?)|(\d(_*\d)*(([fFsFmM])|(([eE](\+|-)?\d(_*\d)*)([fFsFmM])?)))|(0[bB](_*[01])+(([lL][uU]?)|([uU][lL]?))?)|(0[xX](_*([\dA-Fa-f]))+(([lL][uU]?)|([uU][lL]?))?)|(\d(_*\d)*(([lL][uU]?)|([uU][lL]?))?)))</string>
          <key>name</key>
          <string>constant.numeric.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>parentheses</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#parentheses__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>parentheses__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>simple_string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#simple_string__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>simple_string__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#escaped_char</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}])</string>
          <key>name</key>
          <string>string.quoted.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>statement</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#block</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#statement_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#statement_punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
       </array>
    </dict>
    <key>statement_keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(const|else|global|if|return)\b)</string>
          <key>name</key>
          <string>keyword.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>statement_punctuation</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(;|([\x{002b}\-\x{0026}\x{007c}\x{007e}]|&lt;&lt;|&gt;&gt;|\?\?)?=)</string>
          <key>name</key>
          <string>punctuation.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#verbatim_string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#simple_string</string>
        </dict>
       </array>
    </dict>
    <key>using</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(using)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#using__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>using__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(static)</string>
          <key>name</key>
          <string>keyword.VooDo</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#builtin_type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#using_invalid_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#using_punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#invalid</string>
        </dict>
       </array>
    </dict>
    <key>using_invalid_keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(as|const|default|else|false|global|glob|if|init|in|is|new|null|out|ref|return|true|var)\b)</string>
          <key>name</key>
          <string>invalid.broken.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>using_punctuation</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([.\x{002c}\x{003a}\x{003c}\x{003e}\x{003d}])</string>
          <key>name</key>
          <string>punctuation.VooDo</string>
        </dict>
       </array>
    </dict>
    <key>verbatim_string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(@&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#verbatim_string__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;(?!&quot;))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.VooDo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>verbatim_string__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(&quot;&quot;)</string>
          <key>name</key>
          <string>constant.character.escape.VooDo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}])</string>
          <key>name</key>
          <string>string.quoted.VooDo</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
